### ISSUE TITLE
Loggly: MappingConflict

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#231]
Raw message:
```json
{"level":"warn","error":"Internal server error\n","options":{"uri":"POST https://www.example.com/rpc/null","rpc":"CM_Janus_RpcEndpoints.removeStream [6aRK1Fbf12DHraQ,eW.lQlU-Onyv45lH9fx1.w__,04d0cdf8-15ab-4202-883b-fb252e1bcc24]"},"message":"cm-api request failed"}
```

![screen shot 2016-04-05 at 09 59 08](https://cloud.githubusercontent.com/assets/360800/14275023/1ec7211a-fb15-11e5-934a-578d649950d9.png)

What is causing this?

**Comment by vogdb** [comment]
This happens due to changed format of log message.
For example If first send the field "message" as string: `{"message":"hello world"}`. Then sent in something like `{"message":{"0":"config: unknown configuration option: foo"},"timestamp":"2015-04-07T13:22:34.538Z"}` going from a string to a nested object. Such change causes this error.

Loggly index rolls over every 1-2 days (in most cases just 24 hours). So usually those errors vanish after that time, if the change of format was persistent. If error does not vanish during that time then it means that the format of message is not coherent and we need to change it.

**Comment by vogdb** [comment]
I see that the message, that you have posted, has vanished from logs:
```json
{"level":"warn","error":"Internal server error\n","options":{"uri":"POST https://www.example.com/rpc/null","rpc":"CM_Janus_RpcEndpoints.removeStream [6aRK1Fbf12DHraQ,eW.lQlU-Onyv45lH9fx1.w__,04d0cdf8-15ab-4202-883b-fb252e1bcc24]"},"message":"cm-api request failed"}
```

But we still have such error from log messages like cause their format is very incoherent:
```json
{"level":"debug","message":"-> browser"
```
```json
{"level":"debug","message":"<- janus"
```

I think that we will deal with them in #232

**Comment by njam** [comment]
Oh, thanks for the research!
I see you created a "saved search" in loggly to see them. Let's keep this ticket open until we've resolve this fully.

**Comment by njam** [comment]
Errors are currently gone.
Loggly told me we can use the "events" endpoint (RSID) to figure out *which* field caused the problems:

---
The field search using API could provide you the information you need:

https://www.loggly.com/docs/api-retrieving-data/



Below is an example use of field search using api: 

curl -u USERNAME:PASSWORD! "http://SUBDOMAIN.loggly.com/apiv2/search?q=http.clientHost:"*"&from=-5h&until=now&size=10"
{
"rsid": {
"status": "SCHEDULED",
"date_from": 1453217709233,
"elapsed_time": 0.017214059829711914,
"date_to": 1453235709233,
"id": "228602874"
}
}



then, 


curl -u USERNAME:PASSWORD "http://SUBDOMAIN.loggly.com/apiv2/fields?q=http.clientHost:"*"&from=-5h&until=now&size=10"

{
"name": "derived.status"
},
{
"name": "derived.request_id"
},
{
"name": "derived.path"
},

**Comment by tomaszdurka** [comment]
Closable?

**Comment by vogdb** [comment]
I guess we can but this error can easily repeat again. This mapping conflict is a feature more. Lets close.
